### ISSUE TITLE
Packaging CI is running in fork repositories

### ISSUE THREAD

**Issue by mmurooka** [isri-aist/QpSolverCollection#13]
https://github.com/mmurooka/QpSolverCollection/actions/runs/3667418654/jobs/6199881734#step:3:65

I think it should be disabled.

**Comment by gergondet** [comment]
This should be fixed by the commit above (please rebase your branch to see the effet)

I only disable the upload step because I have found it useful in the past to keep the packaging job active (the packaging environment is more isolated than the regular CI environment and this helps to detect when dependencies are not specified correctly for the package we are building or when we are using incompatible CMake features)

**Comment by mmurooka** [comment]
@gergondet  Thank you, it worked. https://github.com/mmurooka/QpSolverCollection/actions/runs/3671841331
